=== mfdogalindo/UC_SEMANTIC_WEB/TALLER_02 - DTD/sensors.dtd
<!ELEMENT sensors (sensor+)>
<!ELEMENT sensor (identification, data+)>
<!ELEMENT identification (uuidV4, ipV4?, ipV6?, user, location?, sensortype+)>
<!ELEMENT uuidV4 (#PCDATA)>
<!ELEMENT ipV4 (#PCDATA)>
<!ELEMENT ipV6 (#PCDATA)>
<!ELEMENT user (#PCDATA)>
<!ELEMENT sensortype (#PCDATA)>
<!ATTLIST sensortype
dimensions (1 | 2 | 3) #REQUIRED
resolution CDATA #REQUIRED
signed  (true | false) "true"
unit CDATA #REQUIRED>
<!ELEMENT location (latitude, longitude)>
<!ELEMENT latitude (#PCDATA)>
<!ELEMENT longitude (#PCDATA)> 
<!ELEMENT data (#PCDATA)>
<!ATTLIST data
type CDATA #REQUIRED
dimension CDATA #REQUIRED>

=== mfdogalindo/UC_SEMANTIC_WEB/TALLER_02 - DTD/sensors.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE sensors SYSTEM "./sensors.dtd">
<sensors>
  <sensor>
    <identification>
      <uuidV4>fc19db85-ef60-4f1f-ad61-97ab5d2ffa1a</uuidV4>
      <ipV4>10.10.0.123</ipV4>
      <ipV6>2001:0db8:85a3:08d3:1319:8a2e:0370:7334</ipV6>
      <user>manuelgalindo@example.edu</user>
      <sensortype dimensions="3" resolution="16" unit="m/s^2">
        accelerometer
      </sensortype>
      <sensortype dimensions="3" resolution="16" unit="°/s">
        gyroscope
      </sensortype>
      <sensortype dimensions="1" resolution="12" signed="false" unit="°C">
        thermal
      </sensortype>
    </identification>
    <data type="accelerometer" dimension="1">
      0x00
    </data>
    <data type="accelerometer" dimension="2">
      0x03
    </data>
    <data type="accelerometer" dimension="3">
      0x0F
    </data>
    <data type="gyroscope" dimension="1">
      0x0F
    </data>
    <data type="gyroscope" dimension="2">
      0x07
    </data>
    <data type="gyroscope" dimension="3">
      0xFA
    </data>
    <data type="thermal" dimension="1">
      0xFA
    </data>
  </sensor>

  <sensor>
    <identification>
      <uuidV4>d0e4cb91-5191-44d4-a943-02ef25a82310</uuidV4>
      <user>manuelgalindo@example.edu</user>
      <location>
        <latitude>0</latitude>
        <longitude>0</longitude>
      </location>
      <sensortype dimensions="1" resolution="12" signed="false" unit="°C">
        thermal
      </sensortype>
    </identification>
    <data type="thermal" dimension="1">
      0xFA
    </data>
  </sensor>

</sensors>
