=== mfdogalindo/UC_SEMANTIC_WEB/TALLER_03 - XPath/devices.dtd
<!ELEMENT devices (device+)>
<!ELEMENT device (identification, sensor+)>
<!ELEMENT identification (uuid, ip?, user, location?)>
<!ELEMENT uuid (#PCDATA)>
<!ATTLIST uuid version (1 | 4) #REQUIRED>
<!ELEMENT ip (#PCDATA)>
<!ATTLIST ip version (4 | 6) #REQUIRED>
<!ELEMENT user (#PCDATA)>
<!ATTLIST user type (email | uuid) #REQUIRED>
<!ELEMENT location (latitude, longitude, altutide?)>
<!ELEMENT latitude (#PCDATA)>
<!ELEMENT longitude (#PCDATA)>
<!ELEMENT altutide (#PCDATA)>
<!ELEMENT sensor (sample*)>
<!ATTLIST sample timestamp CDATA #REQUIRED>
<!ELEMENT sample (data+)>
<!ATTLIST sensor
    type CDATA #REQUIRED
    dimensions (1 | 2 | 3) #REQUIRED
    resolution CDATA #REQUIRED
    signed (true | false) "true"
    unit CDATA #REQUIRED
>
<!ELEMENT data (#PCDATA)>
<!ATTLIST data dimension (1 | 2 | 3) #REQUIRED>
<!ATTLIST data dimension (1 | 2 | 3) #REQUIRED>

=== mfdogalindo/UC_SEMANTIC_WEB/TALLER_03 - XPath/devices.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE devices SYSTEM "http://raw.githubusercontent.com/mfdogalindo/UC_SEMANTIC_WEB/master/TALLER_03%20-%20XPath/devices.dtd">
<devices>
  <device>
    <identification>
      <uuid version="4">fc19db85-ef60-4f1f-ad61-97ab5d2ffa1a</uuid>
      <ip version="4">10.10.0.123</ip>
      <user type="email">manuelgalindo@example.edu</user>
    </identification>

    <sensor type="accelerometer" dimensions="3" resolution="16" unit="m/s^2">
      <sample timestamp="1632437191">
        <data dimension="1">0x00</data>
        <data dimension="2">0x03</data>
        <data dimension="3">0x0F</data>
      </sample>
      <sample timestamp="1632437194">
        <data dimension="1">0x00</data>
        <data dimension="2">0x03</data>
        <data dimension="3">0x0F</data>
      </sample>
    </sensor>

    <sensor type="gyroscope" dimensions="3" resolution="16" unit="째/s">
      <sample timestamp="1632437191">
        <data dimension="1">0x00</data>
        <data dimension="2">0x03</data>
        <data dimension="3">0x0F</data>
      </sample>
    </sensor>

    <sensor type="thermal" dimensions="1" resolution="12" signed="false" unit="째C">
      <sample timestamp="1632437191">
        <data dimension="1">0x00</data>
      </sample>
    </sensor>

    <sensor type="thermal" dimensions="1" resolution="16" signed="false" unit="째C"></sensor>

  </device>

  <device>
    <identification>
      <uuid version="4">d0e4cb91-5191-44d4-a943-02ef25a82310</uuid>
      <user type="email">manuelgalindo@example.edu</user>
      <location>
        <latitude>0</latitude>
        <longitude>0</longitude>
      </location>
    </identification>

    <sensor type="thermal" dimensions="1" resolution="12" signed="false" unit="째C">
      <sample timestamp="1632437202">
        <data dimension="1">0xFA</data>
      </sample>
    </sensor>
  </device>
</devices>
